name: Pull request review issues creation
on: 
  pull_request_review:
    types: [submitted]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Run my Python Action
        uses: ./  # Use path if local, or username/repo@tag if published
        with:
          azure_ai_project_endpoint: ${{ secrets.AZURE_AI_PROJECT_ENDPOINT }}
          model_deployment_name: "gpt-4.1"