name: Pull request review issues creation
on: 
  pull_request_review:
    types: [submitted]

jobs:
  test_action:
    if: contains(github.event.pull_request.labels.*.name, 'neurodiversity-check')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run my Python Action
        uses: ./
        with:
          azure_ai_project_endpoint: ${{ secrets.AZURE_AI_PROJECT_ENDPOINT }}
          model_deployment_name: "gpt-4.1"